-- Quartz 크론 스케줄 추출 예시
SELECT
  t.TRIGGER_NAME,
  t.TRIGGER_GROUP,
  t.JOB_NAME,
  t.JOB_GROUP,
  ct.CRON_EXPRESSION
FROM QRTZ_TRIGGERS t
JOIN QRTZ_CRON_TRIGGERS ct
  ON t.TRIGGER_NAME = ct.TRIGGER_NAME
 AND t.TRIGGER_GROUP = ct.TRIGGER_GROUP
WHERE t.TRIGGER_STATE = 'WAITING';
