# Apply Windows developer environment variables to MSYS2 zsh.
# - Generates ~/.zshrc.d/windows_env.sh
# - Ensures ~/.zshrc sources it
# - Writes inventory and backup metadata to .gcx/state

$ErrorActionPreference = 'Stop'

function Find-RepoRoot {
    param([string]$start)
    $root = $start
    while ($root -and -not (Test-Path (Join-Path $root '.claude\\settings.json'))) {
        $root = Split-Path -Parent $root
    }
    return $root
}

$root = Find-RepoRoot -start $PSScriptRoot
if (-not $root) {
    Write-Error 'Could not find .claude/settings.json. Run this script from inside the repo.'
    exit 1
}

$backupDir = Join-Path $root '.gcx\\state'
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null

$msysHome = "C:\\msys64\\home\\$env:USERNAME"
if (-not (Test-Path $msysHome)) {
    Write-Error "MSYS2 home not found: $msysHome"
    exit 1
}

$envDir = Join-Path $msysHome '.zshrc.d'
$envFile = Join-Path $envDir 'windows_env.sh'
$zshrcPath = Join-Path $msysHome '.zshrc'

# Collect Windows env vars (machine + user, user wins)
$envTable = @{}
$machine = [Environment]::GetEnvironmentVariables('Machine')
foreach ($k in $machine.Keys) { $envTable[$k] = $machine[$k] }
$user = [Environment]::GetEnvironmentVariables('User')
foreach ($k in $user.Keys) { $envTable[$k] = $user[$k] }
$process = [Environment]::GetEnvironmentVariables('Process')
foreach ($k in $process.Keys) {
    if (-not $envTable.ContainsKey($k)) { $envTable[$k] = $process[$k] }
}

$allVars = $envTable.Keys | Sort-Object

# Common developer env vars
$common = @(
    'JAVA_HOME','JDK_HOME','ANDROID_HOME','ANDROID_SDK_ROOT',
    'PYTHONHOME','PYTHONPATH','PIP_INDEX_URL','PIP_EXTRA_INDEX_URL','PIP_TRUSTED_HOST',
    'VIRTUAL_ENV','VIRTUALENVWRAPPER','CONDA_PREFIX','CONDA_DEFAULT_ENV',
    'NODE_PATH','NVM_HOME','NVM_SYMLINK','NPM_CONFIG_PREFIX','NPM_CONFIG_CACHE',
    'PNPM_HOME','YARN_CACHE_FOLDER','YARN_PREFIX',
    'CARGO_HOME','RUSTUP_HOME',
    'GOPATH','GOROOT','GOBIN','GOPROXY','GOPRIVATE',
    'MAVEN_HOME','GRADLE_HOME','DOTNET_ROOT','DOTNET_CLI_HOME',
    'KUBECONFIG','KUBE_CONFIG_PATH',
    'DOCKER_HOST','DOCKER_CERT_PATH','DOCKER_TLS_VERIFY',
    'AWS_PROFILE','AWS_DEFAULT_PROFILE','AWS_REGION','AWS_DEFAULT_REGION',
    'AZURE_CONFIG_DIR',
    'GOOGLE_APPLICATION_CREDENTIALS','GOOGLE_CLOUD_PROJECT'
)

# Recommended (if present)
$recommended = @(
    'OPENAI_API_KEY','ANTHROPIC_API_KEY','GEMINI_API_KEY',
    'CLAUDE_API_KEY','CODEX_API_KEY',
    'CI','TF_VAR_region','TF_VAR_project','TERRAFORM_CONFIG'
)

$allowListPath = Join-Path $backupDir 'dev_env_allowlist.txt'
if (-not (Test-Path $allowListPath)) {
    @'
# Add extra env var names to include (one per line).
# Lines starting with # are ignored.
# Example:
# MY_COMPANY_TOKEN
# CUSTOM_SDK_HOME
'@ | Set-Content -Path $allowListPath -Encoding UTF8
}

$extra = @()
foreach ($line in Get-Content -Path $allowListPath -ErrorAction SilentlyContinue) {
    $trim = $line.Trim()
    if ($trim -and -not $trim.StartsWith('#')) { $extra += $trim }
}

$want = @($common + $recommended + $extra) | Select-Object -Unique
$selected = @()
foreach ($name in $want) {
    if ($envTable.ContainsKey($name)) { $selected += $name }
}
$recommendedNotSet = $want | Where-Object { -not $envTable.ContainsKey($_) }

# Backup existing env file and zshrc
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$envFileBackup = $null
if (Test-Path $envFile) {
    $envFileBackup = Join-Path $backupDir ("windows_env.sh.bak-$timestamp")
    Copy-Item -Path $envFile -Destination $envFileBackup -Force
}

$zshrcBackup = $null
if (Test-Path $zshrcPath) {
    $zshrcBackup = Join-Path $backupDir ("zshrc.bak-$timestamp")
    Copy-Item -Path $zshrcPath -Destination $zshrcBackup -Force
}

New-Item -ItemType Directory -Force -Path $envDir | Out-Null

# Write inventory payload
$selectedValues = @{}
foreach ($name in $selected) { $selectedValues[$name] = $envTable[$name] }
$inventory = @{
    timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    msysHome = $msysHome
    selectedValues = $selectedValues
    recommendedNotSet = $recommendedNotSet
    windowsPath = $envTable['Path']
    allowListPath = $allowListPath
    allVars = $allVars
}
$inventoryPath = Join-Path $backupDir "windows_env_inventory.json"
$inventory | ConvertTo-Json -Depth 6 | Set-Content -Path $inventoryPath -Encoding UTF8

# Generate windows_env.sh via Python (safe shell quoting)
$pyPath = Join-Path $backupDir "write_windows_env.py"
@'
import json, pathlib, sys

def sh_quote(s: str) -> str:
    return "'" + s.replace("'", "'\"'\"'") + "'"

payload = json.loads(pathlib.Path(sys.argv[1]).read_text(encoding="utf-8-sig"))
selected = payload.get("selectedValues", {})
recommended_not_set = payload.get("recommendedNotSet", [])
windows_path = payload.get("windowsPath")

lines = []
lines.append("# Generated by GCX apply-msys2-win-env.ps1")
lines.append("# This file is sourced by ~/.zshrc")
lines.append("export GCX_WINDOWS_ENV_SYNC=1")
lines.append("")

for name in sorted(selected.keys()):
    val = selected[name]
    if val is None:
        continue
    lines.append(f"export {name}={sh_quote(str(val))}")

if windows_path:
    lines.append("")
    lines.append("# Windows PATH import (requires cygpath)")
    lines.append("if command -v cygpath >/dev/null 2>&1; then")
    lines.append(f"  _GCX_WIN_PATH={sh_quote(str(windows_path))}")
    lines.append("  if [ -n \"$ZSH_VERSION\" ]; then")
    lines.append("    _gcx_parts=(${(s:;:)_GCX_WIN_PATH})")
    lines.append("  else")
    lines.append("    IFS=';' read -r -a _gcx_parts <<< \"$_GCX_WIN_PATH\"")
    lines.append("  fi")
    lines.append("  for _p in \"${_gcx_parts[@]}\"; do")
    lines.append("    [ -z \"$_p\" ] && continue")
    lines.append("    _u=$(cygpath -u \"$_p\" 2>/dev/null) || continue")
    lines.append("    case \":$PATH:\" in")
    lines.append("      *\":$_u:\"*) ;;")
    lines.append("      *) PATH=\"$_u:$PATH\" ;;")
    lines.append("    esac")
    lines.append("  done")
    lines.append("  unset _gcx_parts _p _u _GCX_WIN_PATH")
    lines.append("fi")

if recommended_not_set:
    lines.append("")
    lines.append("# Recommended variables (not set in Windows env):")
    for name in sorted(recommended_not_set):
        lines.append(f"# export {name}='...'" )

pathlib.Path(sys.argv[2]).write_text("\n".join(lines) + "\n", encoding="utf-8")
'@ | Set-Content -Path $pyPath -Encoding UTF8

python $pyPath $inventoryPath $envFile
if ($LASTEXITCODE -ne 0) { throw "Python failed to generate $envFile" }
Remove-Item -Path $pyPath -Force

# Ensure ~/.zshrc sources the env file
$blockStart = '# >>> GCX Windows Env (auto-generated)'
$blockEnd = '# <<< GCX Windows Env'
$block = @"
$blockStart
if [ -f ~/.zshrc.d/windows_env.sh ]; then
  source ~/.zshrc.d/windows_env.sh
fi
$blockEnd
"@

if (Test-Path $zshrcPath) {
    $zshrcContent = Get-Content -Path $zshrcPath -Raw
    if ($zshrcContent -notmatch [regex]::Escape($blockStart)) {
        Add-Content -Path $zshrcPath -Value "`n$block"
    }
} else {
    Set-Content -Path $zshrcPath -Value $block -Encoding UTF8
}

# Backup metadata
$backupMeta = @{
    timestamp = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    envFile = $envFile
    envFileBackup = $envFileBackup
    zshrcPath = $zshrcPath
    zshrcBackup = $zshrcBackup
    inventoryPath = $inventoryPath
}
$backupPath = Join-Path $backupDir 'msys2_win_env_backup.json'
$backupMeta | ConvertTo-Json -Depth 6 | Set-Content -Path $backupPath -Encoding UTF8

Write-Host "Applied: $envFile"
Write-Host "Inventory: $inventoryPath"
Write-Host "Backup: $backupPath"
Write-Host "Restart MSYS2 zsh sessions to apply."
